### PR TITLE
Expo cleanup

### PR DESCRIPTION
**Pull request by Aayush-S**
- Updated file and folder structure to match other repos (Registration, livesite, etc)
- Removed the Server folder (backend moved into API repo)

Might be able to remove the .yamls and craco.config.js files

### CODE REVIEW

**Comment by Roshan-D** [comment]
Really awesome work! Tbh I haven't really worked with timber so you kind of the boss on this but here's a couple quick things:

Remove:
- .github folder (since we aren't using beekeeper for deployment anymore)
- deployment.yaml
- cloudbuild.yaml
- Dockerfile
**^ lmk if there's any reason you kept these**

- commit the .env file (no real sensitive info)

**Comment by ayush-goyal** [comment]
Agree with @Roshan-D , everything else looks good. Go ahead and delete the extra files too while ur at it.

**Review by ayush-goyal — CHANGES_REQUESTED** [review]
Delete these files

deployment.yaml

cloudbuild.yaml

Dockerfile

commit the .env file (no real sensitive info)

**Review by Roshan-D — APPROVED** [review]
fire

**Pull request merged**
